// Code generated by mockery v2.20.0. DO NOT EDIT.

package mock

import (
	context "context"

	service "github.com/quocdaitrn/cp-auth/domain/service"
	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// IntrospectToken provides a mock function with given fields: ctx, req
func (_m *AuthService) IntrospectToken(ctx context.Context, req *service.IntrospectTokenRequest) (*service.IntrospectTokenResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *service.IntrospectTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.IntrospectTokenRequest) (*service.IntrospectTokenResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *service.IntrospectTokenRequest) *service.IntrospectTokenResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.IntrospectTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *service.IntrospectTokenRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, req
func (_m *AuthService) Login(ctx context.Context, req *service.LoginRequest) (*service.LoginResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *service.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.LoginRequest) (*service.LoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *service.LoginRequest) *service.LoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *service.LoginRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, req
func (_m *AuthService) Register(ctx context.Context, req *service.RegisterRequest) (*service.RegisterResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *service.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.RegisterRequest) (*service.RegisterResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *service.RegisterRequest) *service.RegisterResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *service.RegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAuthService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthService(t mockConstructorTestingTNewAuthService) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
