// Code generated by mockery v2.20.0. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// Hasher is an autogenerated mock type for the Hasher type
type Hasher struct {
	mock.Mock
}

// CompareHashPassword provides a mock function with given fields: hashedPassword, salt, password
func (_m *Hasher) CompareHashPassword(hashedPassword string, salt string, password string) bool {
	ret := _m.Called(hashedPassword, salt, password)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = rf(hashedPassword, salt, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// HashPassword provides a mock function with given fields: salt, password
func (_m *Hasher) HashPassword(salt string, password string) (string, error) {
	ret := _m.Called(salt, password)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(salt, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(salt, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(salt, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RandomStr provides a mock function with given fields: length
func (_m *Hasher) RandomStr(length int) (string, error) {
	ret := _m.Called(length)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (string, error)); ok {
		return rf(length)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(length)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(length)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewHasher interface {
	mock.TestingT
	Cleanup(func())
}

// NewHasher creates a new instance of Hasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHasher(t mockConstructorTestingTNewHasher) *Hasher {
	mock := &Hasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
