// Code generated by mockery v2.20.0. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, firstName, lastName, email
func (_m *UserRepo) CreateUser(ctx context.Context, firstName string, lastName string, email string) (uint, error) {
	ret := _m.Called(ctx, firstName, lastName, email)

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (uint, error)); ok {
		return rf(ctx, firstName, lastName, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) uint); ok {
		r0 = rf(ctx, firstName, lastName, email)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, firstName, lastName, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepo(t mockConstructorTestingTNewUserRepo) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
